### ISSUE TITLE
Upgrade KnowPulse to Tripal 3

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/KnowPulse#9]
This is dependant upon a lot of other modules being upgraded to Tripal 3.

That said, there are also some updates to our chado database that need to be done. Specifically,
- [ ] The project table is now going to be used for Research projects, experiments and genome assemblies. We need to add project properties to specify which of these three each current project is.
- [ ] We need to create assembly projects for all our assemblies and link them to their sequence features.
- [ ] We are switching to all variants being of type sequence_variant and the type of variant (SNP, MNP, Indel) being saved in featureprop to match genetic markers.
- [ ] There are currently 2 sets of the bean genome assembly in KnowPulse, one needs to go.
- [ ] Germplasm are switching to the crop germplasm ontology. Type_ids need to be updated accordingly.
- [ ] Crosses will be combined to a single type with single, double, or triple stored as a property.
- [ ] Other stock types will also be combined.

Essentially, we are cleaning up all the cruft and unifying our chado database for the migration :-) We also moving towards using more published ontologies.

**Comment by laceysanderson** [comment]
## Ontologies Used
- [x] Sequence Ontology (SO): Used for chado.feature types (gene, sequence_variant, genetic_marker, chromosome, QTL, etc.) and variant types (SNP, MNP, Indel).
- [ ] Semantic Science Ontology (SIO): Used for categorizing projects (2 terms only). 
- [ ] Tripal Publication Ontology (TPUB): Used for the publication content type, it's types, properties and relationships.
- [ ] Crop Germplasm Ontology (CO_010): Used for stock.types (accession, cultivar, inbred line)
- [ ] Bioinformatics operations, data types, formats, identifiers and topics (EDAM): Genetic map  (data:1278)
- [ ] Gramene Plant Trait Ontology (TO): to annotate phenotypes.
- [ ] Lentil, Chickpea, Common Bean  Crop Ontology: to annotate phenotypes.

**Comment by laceysanderson** [comment]
Commands for cleaning up our Chado Database:
```sql
--Remove invalid cv.
DELETE FROM chado.cvterm WHERE cv_id IN (SELECT cv_id FROM chado.cv WHERE name~'or the item, typically used for adding more specific t');
DELETE FROM chado.cv WHERE name~'or the item, typically used for adding more specific t';
DELETE FROM chado.cv WHERE name~'owl-ontologies';
DELETE FROM chado.cvterm WHERE cv_id IN (SELECT cv_id FROM chado.cv WHERE name='null');
DELETE FROM chado.cv WHERE name='null';

---Remove tripal views integrations.
DELETE FROM tripal_views_join WHERE setup_id IN (SELECT setup_id FROM tripal_views WHERE priority=10);
DELETE FROM tripal_views_handlers WHERE setup_id IN (SELECT setup_id FROM tripal_views WHERE priority=10);
DELETE FROM tripal_views_field WHERE setup_id IN (SELECT setup_id FROM tripal_views WHERE priority=10);
DELETE FROM tripal_views WHERE priority=10;
```

**Comment by laceysanderson** [comment]
I tried the upgrade process documented here: http://tripal.info/tutorials/v3.x/upgrade/2.x-to-3.x.
All modules enabled without error. However, "preparing chado" for use with Tripal 3 produces the following error log:

```
$ drush trp-run-jobs --username=kpadmin --root=/var/www/dev/kp-tripal3

2017-11-15 11:46:28
Tripal Job Launcher
Running as user 'kpadmin'
-------------------
2017-11-15 11:46:28: There are 1 jobs queued.
2017-11-15 11:46:28: Calling: tripal_chado_prepare_chado()
Creating Tripal Materialized Views and Custom Tables...
Loading Ontologies...
Ontology already loaded (skipping): Taxonomic Rank...
Loading ontology: Tripal Contact (14)...
Ontology already loaded (skipping): Tripal Publication...
Ontology already loaded (skipping): Sequence Ontology...
Making semantic connections for Chado tables/fields...
Map Chado Controlled vocabularies to Tripal Terms...
Examining analysis...
Examining biomaterial...
Examining contact...
Examining control...
Examining cvterm...
Examining feature...
Examining featuremap...
Examining genotype...
Examining library...
Examining organism...
Examining phenotype...
Examining phylotree...
Examining project...
Examining protocol...
Examining protocolparam...
Examining pub...
Examining stock...
Examining stockcollection...
Examining studyfactor...
Examining synonym...

Done.
Creating common Tripal Content Types...
exception 'Exception' in /var/www/dev/kp-tripal3/sites/all/modules/contrib/tripal/tripal_chado/includes/setup/tripal_chado.setup.inc:250
Stack trace:
#0 [internal function]: tripal_chado_prepare_chado(Object(TripalJob))
#1 /var/www/dev/kp-tripal3/sites/all/modules/contrib/tripal/tripal/includes/TripalJob.inc(260): call_user_func_array('tripal_chado_pr...', Array)
#2 /var/www/dev/kp-tripal3/sites/all/modules/contrib/tripal/tripal/api/tripal.jobs.api.inc(416): TripalJob->run()
#3 /var/www/dev/kp-tripal3/sites/all/modules/contrib/tripal/tripal/tripal.drush.inc(159): tripal_launch_job(0, NULL, -1, 0)
#4 [internal function]: drush_tripal_trp_run_jobs()
#5 /usr/share/php/drush/includes/command.inc(334): call_user_func_array('drush_tripal_tr...', Array)
#6 /usr/share/php/drush/includes/command.inc(208): _drush_invoke_hooks('trp-run-jobs', Array, 'tripal')
#7 [internal function]: drush_command()
#8 /usr/share/php/drush/includes/command.inc(175): call_user_func_array('drush_command', Array)
#9 /usr/share/php/drush/drush.php(92): drush_dispatch(Array)
#10 /usr/share/php/drush/drush.php(61): _drush_bootstrap_and_dispatch()
#11 /usr/share/php/drush/drush.php(16): drush_main()
#12 {main}
Failed to create content type: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored     [error]
until end of transaction block.
Job execution failed: exception 'Exception' in                                                                                            [error]
/var/www/dev/kp-tripal3/sites/all/modules/contrib/tripal/tripal_chado/includes/setup/tripal_chado.setup.inc:250
Stack trace:
#0 [internal function]: tripal_chado_prepare_chado(Object(TripalJob))
#1 /var/www/dev/kp-tripal3/sites/all/modules/contrib/tripal/tripal/includes/TripalJob.inc(260): call_user_func_array('tripal_chado_pr...',
Array)
#2 /var/www/dev/kp-tripal3/sites/all/modules/contrib/tripal/tripal/api/tripal.jobs.api.inc(416): TripalJob->run()
#3 /var/www/dev/kp-tripal3/sites/all/modules/contrib/tripal/tripal/tripal.drush.inc(159): tripal_launch_job(0, NULL, -1, 0)
#4 [internal function]: drush_tripal_trp_run_jobs()
#5 /usr/share/php/drush/includes/command.inc(334): call_user_func_array('drush_tripal_tr...', Array)
#6 /usr/share/php/drush/includes/command.inc(208): _drush_invoke_hooks('trp-run-jobs', Array, 'tripal')
#7 [internal function]: drush_command()
#8 /usr/share/php/drush/includes/command.inc(175): call_user_func_array('drush_command', Array)
#9 /usr/share/php/drush/drush.php(92): drush_dispatch(Array)
#10 /usr/share/php/drush/drush.php(61): _drush_bootstrap_and_dispatch()
#11 /usr/share/php/drush/drush.php(16): drush_main()
#12 {main}
Custom table, 'contactprop' , already exists. Table structure not changed, but definition array has been saved.                           [status]
Custom table, 'featuremap_dbxref' , already exists. Table structure not changed, but definition array has been saved.                     [status]
Custom table, 'featuremapprop' , already exists. Table structure not changed, but definition array has been saved.                        [status]
Custom table, 'featureposprop' , already exists. Table structure not changed, but definition array has been saved.                        [status]
Custom table, 'pubauthor_contact' , already exists. Table structure not changed, but definition array has been saved.                     [status]
Custom table, 'tripal_gff_temp' , already exists. Table structure not changed, but definition array has been saved.                       [status]
Custom table, 'tripal_gffcds_temp' , already exists. Table structure not changed, but definition array has been saved.                    [status]
Custom table, 'tripal_gffprotein_temp' , already exists. Table structure not changed, but definition array has been saved.                [status]
Materialized view, organism_stock_count, already exists. Skipping creation.                                                               [status]
Materialized view, library_feature_count, already exists. Skipping creation.                                                              [status]
Materialized view, organism_feature_count, already exists. Skipping creation.                                                             [status]
Materialized view, analysis_organism, already exists. Skipping creation.                                                                  [status]
Materialized view, cv_root_mview, already exists. Skipping creation.
```

**Comment by laceysanderson** [comment]
After multiple fixes, I have finally got our Chado database prepared for Tripal 3 :-D. All of the fixes went into Tripal core except for one:

For some reason our content creation fails due to the database transaction used. This happens both during preparation of the database and through the administrative interface. As such we need to comment out the database transaction code in `tripal_create_bundle()`. Since database transactions are generally a good thing and no one else has reported this error, I didn't feel comfortable comiting this fix to core. Patch below:
```patch
diff --git a/tripal/api/tripal.entities.api.inc b/tripal/api/tripal.entities.api.inc
index 3a084c5..685ce06 100755
--- a/tripal/api/tripal.entities.api.inc
+++ b/tripal/api/tripal.entities.api.inc
@@ -378,7 +378,7 @@ function tripal_create_bundle($args, &$error = '') {
   $term_name = $args['term_name'];
   $storage_args = $args['storage_args'];
 
-  $transaction = db_transaction();
+  //$transaction = db_transaction();
   try {
     // First create the TripalVocab if it doesn't already exist.
     $vocab = tripal_load_vocab_entity(array('vocabulary' => $vocabulary));
@@ -445,7 +445,7 @@ function tripal_create_bundle($args, &$error = '') {
     }
   }
   catch (Exception $e) {
-    $transaction->rollback();
+    //$transaction->rollback();
     drupal_set_message(t("Failed to create content type: %message.",
       array('%message' => $e->getMessage())), 'error');
     return FALSE;
```

**Comment by laceysanderson** [comment]
Steps for Upgrade:
1. Follow [Step #1 on tripal.info](http://tripal.info/tutorials/v3.x/upgrade/2.x-to-3.x) with applying the above patch to Tripal 3 before Step 1.8 (preparing chado).
2. Upgrade KP Theme: switch to 7.x-3.x branch (may require re-cloning of repo).
3. Upgrade KP Frontpage: pull new changes.

** I've confirmed all the old searches and node pages work on Tripal 3. This first upgrade is simply to upgrade the backend without any changes to the user experience. **

**Comment by laceysanderson** [comment]
Completing the upgrade on the Production Site!
**This first upgrade is simply to upgrade the backend without any changes to the user experience.**

Confirming all the Tripal 2 pages still work:
- node pages:
   - [ ] feature (X-marker, X-SNP, X-contig)
   - [ ] organism
   - [ ] project
   - [x] stock
   - [x] publication
   - [x] research area
   - [x] sequencing run
- searches
   - [x] feature (X-sequencing, X-sequencing runs, x-markers, X-variants)
   - [x] genotype
   - [x] stock (x-general, x-cross, x-RIL, x-varieties)
   - [x] project
   - [x] publication
- other pages
   - [ ] raw phenotypes (X-Summary, X-Video, X-SPP, X-Backup, upload, download)
   - [x] organism listings
   - [x] cvit.js
   - [x] pos convert
   - [x] vcf export
   - [x] user driven charts
   - [x] JBrowse
   - [x] BLAST
   - [x] tools listing (http://knowpulse.usask.ca/dev/kp-tripal3/data)
   - [x] research (http://knowpulse.usask.ca/dev/kp-tripal3/research/crops)

**Comment by laceysanderson** [comment]
Complete! Portal is as Tripal3 in legacy mode!

**Comment by laceysanderson** [comment]
Still need to clean up our drunken chado.

 - [ ] **Enable KP Entities and load the ontologies submitted :-)**

## Variants:

 - [ ] We are switching to all variants being of type sequence_variant and the type of variant (SNP, MNP, Indel) being saved in featureprop to match genetic markers.

```sql
INSERT INTO chado.featureprop (feature_id, type_id, value) SELECT f.feature_id, (SELECT cvterm_id FROM chado.cvterm WHERE name~'additionalType'), cvt.name FROM chado.feature f LEFT JOIN chado.cvterm cvt ON cvt.cvterm_id=f.type_id WHERE cvt.name IN ('SNP','MNP','Indel');
UPDATE chado.feature SET uniquename=uniquename||'_'||cvt.name FROM chado.cvterm cvt WHERE cvt.cvterm_id=feature.type_id AND feature.name~'TOG' AND cvt.name IN ('SNP','MNP','Indel');
UPDATE chado.feature SET type_id=(SELECT cvterm_id FROM chado.cvterm WHERE name='sequence_variant')
```
Once the switch is done, we need to update the sequence variant search as shown on dev-fresh.

**Comment by laceysanderson** [comment]
Current Status of Pages:
__This list keeps track of existence of the Tripal 3 pages but may not reflect support in the form of searches and integrations with other modules.__
- [x] Organisms => Species
- [x] Publications
- [ ] Projects
- [ ] Genome Assemblies
- [ ] RILs
- [ ] Varieties
- [ ] Crosses
- [ ] Accessions
- [x] Variants
- [x] Markers
- [ ] Sequence pages (contigs, chromosomes, supercontigs)
